### ISSUE TITLE
Return values of actions are not type safe (broadened to Promise<any>)

### ISSUE THREAD

**Issue by unshame** [ktsn/vuex-smart-module#424] opened 2021-04-24 18:35 UTC
When using actions via `root.context(store).actions.bar()` I noticed their return values are always `Promise<any>` which is not type safe.    

I dug a little into this library and found that this is purposefully done by the `Dispatcher` type.  

https://github.com/ktsn/vuex-smart-module/blob/dfb04f1c240c7ef965e774b22f3d4415c829b57c/src/assets.ts#L139  

```typescript
export type Dispatcher<A> = {
  [K in keyof A]: Payload<A[K]> extends never
    ? never
    : MappedFunction<A[K], Promise<any>>
}

```

I managed to make it return the original value by changing the type of Dispatcher

```typescript
type TypesafeDispatcher<A> = {
    [K in keyof A]: Payload<A[K]> extends never
        ? never
        : MappedFunction<A[K], PromisifiedReturnType<A[K]>>
}

type PromisifiedReturnType<T> = T extends (...args: any) => infer R
    ? R extends Promise<any>
        ? R
        : Promise<R>
    : never;
```

This makes it so that the return type of an action is either its original return type (if it's a promise) or its original return type wrapped in a promise.

But now I'm wondering if there was some reason for using `Promise<any>` in the first place?

I can see a couple:

1. Vuex itself uses `Promise<any>` as a return type for actions - but that's not a good reason since this library is supposed to be "completely type safe".
2. Returning values from actions might not be considered a good practice. But in that case returning `Promise<void>` or `Promise<unknown>` - which is what happens if we correctly infer the return types of actions - is still more type safe.

Is there something I'm missing or can this change be implemented safely?

**Comment by ktsn** [comment] 2021-06-04 02:06
Duplicate of #23, #113 and #174


I've changed `Promise<any>` to `Promise<unknown>`

**Closed** 2021-06-04 02:06 UTC
